version: '3.9'
services:

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    # command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --no-use-colors"

  sentry:
    image: 'sentry:latest'
    depends_on:
      - postgres
      - redis
    ports:
      - '9000:9000'
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: ${SENTRY_POSTGRES_HOST}
      SENTRY_POSTGRES_PORT: ${SENTRY_POSTGRES_PORT}
      SENTRY_DB_NAME: ${SENTRY_DB_NAME}
      SENTRY_DB_USER: ${SENTRY_DB_USER}
      SENTRY_DB_PASSWORD: ${SENTRY_DB_PASSWORD}
      SENTRY_REDIS_HOST: ${SENTRY_REDIS_HOST}

#  sentry_worker:
#    image: 'sentry:latest'
#    depends_on:
#      - postgres
#      - redis
#    command: "sentry run worker"
#    environment:
#      SENTRY_SECRET_KEY: 'theSentrySecretKey'
#      SENTRY_POSTGRES_HOST: 'postgres'
#      SENTRY_POSTGRES_PORT: '5432'
#      SENTRY_DB_NAME: 'sentry'
#      SENTRY_DB_USER: 'sentry'
#      SENTRY_DB_PASSWORD: 'sentry'
#      SENTRY_REDIS_HOST: 'redis'
#
#  sentry_cron:
#    image: 'sentry:latest'
#    depends_on:
#      - postgres
#      - redis
#    command: "sentry run cron"
#    environment:
#      SENTRY_SECRET_KEY: 'theSentrySecretKey'
#      SENTRY_POSTGRES_HOST: 'postgres'
#      SENTRY_POSTGRES_PORT: '5432'
#      SENTRY_DB_NAME: 'sentry'
#      SENTRY_DB_USER: 'sentry'
#      SENTRY_DB_PASSWORD: 'sentry'
#      SENTRY_REDIS_HOST: 'redis'
