"""added poshta fields to orders table

Revision ID: 00c2aae735bb
Revises: 2ed5bc393d6a
Create Date: 2024-03-02 17:45:25.855906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c2aae735bb'
down_revision = '2ed5bc393d6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('selected_nova_poshta_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('selected_ukr_poshta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'ukr_poshta', ['selected_ukr_poshta_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'nova_poshta', ['selected_nova_poshta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'selected_ukr_poshta_id')
    op.drop_column('orders', 'selected_nova_poshta_id')
    # ### end Alembic commands ###
