"""added is_authenticated field to orders table

Revision ID: 13f4bd58c9b8
Revises: c72babe5d71d
Create Date: 2024-02-03 17:23:37.732102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f4bd58c9b8'
down_revision = 'c72babe5d71d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_authenticated')
    # ### end Alembic commands ###
