"""create email_addresses table to send messages to moderators

Revision ID: 1ca07d24386e
Revises: 00c2aae735bb
Create Date: 2024-03-16 13:19:12.239594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca07d24386e'
down_revision = '00c2aae735bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('is_send_message', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_addresses_address'), 'email_addresses', ['address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_addresses_address'), table_name='email_addresses')
    op.drop_table('email_addresses')
    # ### end Alembic commands ###
