"""added is_active field to nova_poshta table

Revision ID: 1fb03cc3a1fd
Revises: dc34e0886cef
Create Date: 2024-06-20 12:15:19.620490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb03cc3a1fd'
down_revision = 'dc34e0886cef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nova_poshta', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nova_poshta', 'is_active')
    # ### end Alembic commands ###
