"""create orders table and ordered_products table

Revision ID: 247ea90218c0
Revises: 9d93db8cb9b8
Create Date: 2024-01-18 12:32:45.544615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247ea90218c0'
down_revision = '9d93db8cb9b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordered_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('basket_id', sa.Integer(), nullable=True),
    sa.Column('price_order', sa.Float(), nullable=False),
    sa.Column('payment_type', sa.Enum('cash_on_delivery_np', 'liqpay', name='paymenttypes'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmation_manager', sa.Boolean(), nullable=True),
    sa.Column('confirmation_pay', sa.Boolean(), nullable=True),
    sa.Column('call_manager', sa.Boolean(), nullable=True),
    sa.Column('status_order', sa.Enum('new', 'in_processing', 'shipped', 'delivered', 'cancelled', name='orderstatus'), nullable=True),
    sa.Column('ordered_product_id', sa.Integer(), nullable=True),
    sa.Column('post_type', sa.Enum('nova_poshta', 'ukr_poshta', name='posttype'), nullable=True),
    sa.Column('address_warehouse', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('house_number', sa.String(length=255), nullable=True),
    sa.Column('apartment_number', sa.String(length=255), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('post_code', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
    sa.ForeignKeyConstraint(['ordered_product_id'], ['ordered_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('ordered_products')
    # ### end Alembic commands ###
