"""product create_at, update_at

Revision ID: 2d25a57a3b97
Revises: 723219256cac
Create Date: 2023-07-12 20:53:57.834999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d25a57a3b97'
down_revision = '723219256cac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
