"""added is_delivery field to nova_poshta table

Revision ID: 2ed5bc393d6a
Revises: b417e7e688d7
Create Date: 2024-03-02 17:36:14.004393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed5bc393d6a'
down_revision = 'b417e7e688d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nova_poshta', sa.Column('is_delivery', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nova_poshta', 'is_delivery')
    # ### end Alembic commands ###
