"""remove tables of anonym user

Revision ID: 33d687d819db
Revises: 6fe2fc7b20fc
Create Date: 2024-02-11 09:53:26.444288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d687d819db'
down_revision = '6fe2fc7b20fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket_item_anon_users')
    op.drop_table('basket_anon_users')
    op.drop_table('anonymous_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('anonymous_users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_anon_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='anonymous_users_pkey'),
    sa.UniqueConstraint('user_anon_id', name='anonymous_users_user_anon_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('basket_anon_users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('basket_anon_users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('anonymous_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['anonymous_user_id'], ['anonymous_users.id'], name='basket_anon_users_anonymous_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='basket_anon_users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('basket_item_anon_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('basket_anon_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_id_by_anon_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['basket_anon_user_id'], ['basket_anon_users.id'], name='basket_item_anon_users_basket_anon_user_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='basket_item_anon_users_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='basket_item_anon_users_pkey')
    )
    # ### end Alembic commands ###
