"""remove is_created field from orders table

Revision ID: 39e2c779f7d3
Revises: d113b5a4156c
Create Date: 2024-02-15 23:22:01.186509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e2c779f7d3'
down_revision = 'd113b5a4156c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_created', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
