"""create table of used email tokens

Revision ID: 40df38905f41
Revises: e388d1b62c8d
Create Date: 2024-04-20 17:52:01.203725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40df38905f41'
down_revision = 'e388d1b62c8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_email_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_token', sa.String(length=255), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used_email_tokens')
    # ### end Alembic commands ###
