"""add_field is_active to price

Revision ID: 43428144a079
Revises: b235e0e53aa9
Create Date: 2023-11-27 21:32:55.348042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43428144a079'
down_revision = 'b235e0e53aa9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
