"""added quantity field to basket item

Revision ID: 5369f42c21ba
Revises: ec99fb476df2
Create Date: 2023-11-13 20:05:53.920590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5369f42c21ba'
down_revision = 'ec99fb476df2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket_items', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basket_items', 'quantity')
    # ### end Alembic commands ###
