"""added is_created field to orders table

Revision ID: 5c187d5a55d5
Revises: 33d687d819db
Create Date: 2024-02-11 09:56:54.359897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c187d5a55d5'
down_revision = '33d687d819db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_created', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_created')
    # ### end Alembic commands ###
