"""changed fields of nova_poshta table

Revision ID: 69eaf7fb0a15
Revises: de1722035958
Create Date: 2024-01-04 20:00:31.657459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69eaf7fb0a15'
down_revision = 'de1722035958'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nova_poshta', sa.Column('address_warehouse', sa.String(length=255), nullable=True))
    op.add_column('nova_poshta', sa.Column('area', sa.String(length=255), nullable=True))
    op.add_column('nova_poshta', sa.Column('floor', sa.Integer(), nullable=True))
    op.drop_column('nova_poshta', 'country')
    op.drop_column('nova_poshta', 'office_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nova_poshta', sa.Column('office_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('nova_poshta', sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('nova_poshta', 'floor')
    op.drop_column('nova_poshta', 'area')
    op.drop_column('nova_poshta', 'address_warehouse')
    # ### end Alembic commands ###
