"""remove orders table

Revision ID: 6a67321cf3ee
Revises: 69eaf7fb0a15
Create Date: 2024-02-04 21:28:01.451442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a67321cf3ee'
down_revision = '69eaf7fb0a15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('basket_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_order', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_type', postgresql.ENUM('cash_on_delivery_np', 'liqpay', name='paymenttypes'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('confirmation_manager', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('confirmation_pay', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('call_manager', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status_order', postgresql.ENUM('new', 'in_processing', 'shipped', 'delivered', 'cancelled', name='orderstatus'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], name='orders_basket_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='orders_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='orders_pkey')
    )
    # ### end Alembic commands ###
