"""remove relationship fields anonym user with order

Revision ID: 6fe2fc7b20fc
Revises: 0f91d7a95b0a
Create Date: 2024-02-11 09:49:58.867580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe2fc7b20fc'
down_revision = '0f91d7a95b0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_anonymous_user_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_basket_anon_user_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'anonymous_user_id')
    op.drop_column('orders', 'basket_anon_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('basket_anon_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('anonymous_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_basket_anon_user_id_fkey', 'orders', 'basket_anon_users', ['basket_anon_user_id'], ['id'])
    op.create_foreign_key('orders_anonymous_user_id_fkey', 'orders', 'anonymous_users', ['anonymous_user_id'], ['id'])
    # ### end Alembic commands ###
