"""product popular and quantity

Revision ID: 723219256cac
Revises: 95f0d40be80d
Create Date: 2023-07-12 20:23:49.578479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723219256cac'
down_revision = '95f0d40be80d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('is_popular', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_popular')
    op.drop_column('prices', 'quantity')
    # ### end Alembic commands ###
