"""added star rating for reviews

Revision ID: 7b510eefe8e2
Revises: ef6bb4b54a5d
Create Date: 2023-10-29 20:11:30.065379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b510eefe8e2'
down_revision = 'ef6bb4b54a5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('is_checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'is_checked')
    # ### end Alembic commands ###
