"""transfer promotional from product to price

Revision ID: 7ed158240a29
Revises: 0f7e636a83e8
Create Date: 2023-12-15 23:16:55.548196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed158240a29'
down_revision = '0f7e636a83e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('promotional', sa.Boolean(), nullable=True))
    op.drop_column('products', 'promotional')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('promotional', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('prices', 'promotional')
    # ### end Alembic commands ###
