"""refactor favorites

Revision ID: 7f63aa925970
Revises: cf0518358a0c
Create Date: 2023-07-15 14:02:47.824989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f63aa925970'
down_revision = 'cf0518358a0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorite_items_favorite_id_fkey', 'favorite_items', type_='foreignkey')
    op.drop_table('favorits')
    op.drop_table('favorite_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorits.id'], name='favorite_items_favorite_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='favorite_items_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_items_pkey')
    )
    op.create_table('favorits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorits_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorits_pkey')
    )
    # ### end Alembic commands ###
