"""added tables of models

Revision ID: 803447790abc
Revises:
Create Date: 2023-11-05 11:46:35.131873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803447790abc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('token', sa.String(length=255), nullable=False),
                    sa.Column('added_on', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('token')
    )
    op.create_table('product_categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
    )
    op.create_table('product_sub_categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=150), nullable=False),
                    sa.Column('roles', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('first_name', sa.String(length=150), nullable=False),
                    sa.Column('last_name', sa.String(length=150), nullable=False),
                    sa.Column('patroymic', sa.String(length=150), nullable=True),
                    sa.Column('phone_number', sa.String(length=50), nullable=True),
                    sa.Column('password_checksum', sa.String(length=255), nullable=False),
                    sa.Column('refresh_token', sa.String(length=255), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('is_blocked', sa.Boolean(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
    )
    op.create_table('baskets',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cooperations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('description', sa.String(length=255), nullable=False),
                    sa.Column('check', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=150), nullable=False),
                    sa.Column('description', sa.String(length=400), nullable=False),
                    sa.Column('product_category_id', sa.Integer(), nullable=True),
                    sa.Column('promotional', sa.Boolean(), nullable=True),
                    sa.Column('new_product', sa.Boolean(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('is_popular', sa.Boolean(), nullable=True),
                    sa.Column('is_favorite', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basket_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('basket_id', sa.Integer(), nullable=True),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('favorite_id', sa.Integer(), nullable=True),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], ),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nova_poshta',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=True),
                    sa.Column('address', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('basket_id', sa.Integer(), nullable=True),
                    sa.Column('price_order', sa.Float(), nullable=False),
                    sa.Column('payment_type', sa.Enum('cash_on_delivery_np', 'liqpay', name='paymenttype'), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('confirmation_manager', sa.Boolean(), nullable=True),
                    sa.Column('confirmation_pay', sa.Boolean(), nullable=True),
                    sa.Column('call_manager', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('weight', sa.String(length=20), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('old_price', sa.Float(), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_subcategory_association',
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('subcategory_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.ForeignKeyConstraint(['subcategory_id'], ['product_sub_categories.id'], )
    )
    op.create_table('reviews',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('rate', sa.Enum('five_stars', 'four_stars', 'three_stars', 'two_stars', 'one_star', name='rate'), nullable=True),
                    sa.Column('description', sa.String(length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('is_checked', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ukr_poshta',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=True),
                    sa.Column('address', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('review_id', sa.Integer(), nullable=True),
                    sa.Column('image_url', sa.String(length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('description', sa.String(length=255), nullable=False),
                    sa.Column('image_type', sa.Enum('product', 'review', name='imagetype'), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('main_image', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('image_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('ukr_poshta')
    op.drop_table('reviews')
    op.drop_table('product_subcategory_association')
    op.drop_table('prices')
    op.drop_table('orders')
    op.drop_table('nova_poshta')
    op.drop_table('favorite_items')
    op.drop_table('basket_items')
    op.drop_table('products')
    op.drop_table('posts')
    op.drop_table('favorites')
    op.drop_table('cooperations')
    op.drop_table('baskets')
    op.drop_table('users')
    op.drop_table('product_sub_categories')
    op.drop_table('product_categories')
    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
