"""changed type of rate field

Revision ID: 8b039d7f2fb9
Revises: 09007ede6a12
Create Date: 2023-10-29 23:06:30.852774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b039d7f2fb9'
down_revision = '09007ede6a12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE reviews ALTER COLUMN rate TYPE rate USING rate::rate")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE reviews ALTER COLUMN rate TYPE text USING rate::text")
    # ### end Alembic commands ###
