"""Refactor images

Revision ID: 926100626ef8
Revises: 56fa40e5cb9d
Create Date: 2023-09-17 16:28:03.710896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926100626ef8'
down_revision = '56fa40e5cb9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE imagetype AS ENUM('product', 'review')")
    op.add_column('images', sa.Column('image_type', sa.Enum('product', 'review', name='imagetype'), nullable=True))
    op.add_column('images', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'is_deleted')
    op.drop_column('images', 'image_type')
    op.execute("DROP TYPE imagetype")
    # ### end Alembic commands ###
