"""product_category 100 simbols

Revision ID: 95f0d40be80d
Revises: 0765abaf2581
Create Date: 2023-07-08 00:10:44.567311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f0d40be80d'
down_revision = '0765abaf2581'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
