"""added review fields to image model

Revision ID: a2d2a5b81f52
Revises: a7e9327972ea
Create Date: 2023-11-04 12:54:57.627746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d2a5b81f52'
down_revision = 'a7e9327972ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('review_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'reviews', ['review_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reviews_image_id_fkey', 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reviews_image_id_fkey', 'reviews', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'review_id')
    # ### end Alembic commands ###
