"""added quantity field to basket items table

Revision ID: b235e0e53aa9
Revises: d0171fafb624
Create Date: 2023-11-14 23:29:32.850750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b235e0e53aa9'
down_revision = 'd0171fafb624'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket_items', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basket_items', 'quantity')
    # ### end Alembic commands ###
