"""add_field price_id_by_the_user for basketitem

Revision ID: b270a60b7522
Revises: 43428144a079
Create Date: 2023-11-27 23:58:41.448834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b270a60b7522'
down_revision = '43428144a079'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket_items', sa.Column('price_id_by_the_user', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basket_items', 'price_id_by_the_user')
    # ### end Alembic commands ###
