"""product description 400

Revision ID: b72d2993ad1d
Revises: b68447011d20
Create Date: 2023-07-07 22:22:13.193740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72d2993ad1d'
down_revision = 'b68447011d20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
