"""added fields of data of anonym user

Revision ID: c72babe5d71d
Revises: e717fe60e2a5
Create Date: 2024-02-01 22:49:54.763926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72babe5d71d'
down_revision = 'e717fe60e2a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('first_name_anon_user', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('last_name_anon_user', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('email_anon_user', sa.String(length=150), nullable=True))
    op.add_column('orders', sa.Column('phone_number_anon_user', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'orders', ['email_anon_user'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'phone_number_anon_user')
    op.drop_column('orders', 'email_anon_user')
    op.drop_column('orders', 'last_name_anon_user')
    op.drop_column('orders', 'first_name_anon_user')
    # ### end Alembic commands ###
