"""price is deleted

Revision ID: cf0518358a0c
Revises: 2d25a57a3b97
Create Date: 2023-07-12 22:29:17.585267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0518358a0c'
down_revision = '2d25a57a3b97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'is_deleted')
    # ### end Alembic commands ###
