"""added extra fields for another recipient to orders table

Revision ID: d113b5a4156c
Revises: e002bab14e1f
Create Date: 2024-02-13 12:41:17.355689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd113b5a4156c'
down_revision = 'e002bab14e1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_another_recipient', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('full_name_another_recipient', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('phone_number_another_recipient', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('comment', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'comment')
    op.drop_column('orders', 'phone_number_another_recipient')
    op.drop_column('orders', 'full_name_another_recipient')
    op.drop_column('orders', 'is_another_recipient')
    # ### end Alembic commands ###
