"""added settlement_ref field to nova_poshta table

Revision ID: dc34e0886cef
Revises: e174f9c90007
Create Date: 2024-06-11 19:59:55.705697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc34e0886cef'
down_revision = 'e174f9c90007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nova_poshta', sa.Column('settlement_ref', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nova_poshta', 'settlement_ref')
    # ### end Alembic commands ###
