"""image_url unique False

Revision ID: de1722035958
Revises: e46cf44fc4be
Create Date: 2023-12-25 16:51:35.754670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1722035958'
down_revision = 'e46cf44fc4be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_image_url_key', 'images', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('images_image_url_key', 'images', ['image_url'])
    # ### end Alembic commands ###
