"""added notes field for admin to orders table

Revision ID: e388d1b62c8d
Revises: 1ca07d24386e
Create Date: 2024-03-17 12:36:40.801304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e388d1b62c8d'
down_revision = '1ca07d24386e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('notes_admin', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'notes_admin')
    # ### end Alembic commands ###
