"""created association tables of postal offices

Revision ID: e46cf44fc4be
Revises: b0373e314cf9
Create Date: 2023-12-21 21:15:23.450902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46cf44fc4be'
down_revision = 'b0373e314cf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_novaposhta_association',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('nova_poshta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nova_poshta_id'], ['nova_poshta.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], )
    )
    op.create_table('post_ukrposhta_association',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('ukr_poshta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['ukr_poshta_id'], ['ukr_poshta.id'], )
    )
    op.drop_constraint('posts_ukr_poshta_id_fkey', 'posts', type_='foreignkey')
    op.drop_constraint('posts_nova_poshta_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'ukr_poshta_id')
    op.drop_column('posts', 'nova_poshta_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('nova_poshta_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('ukr_poshta_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_nova_poshta_id_fkey', 'posts', 'nova_poshta', ['nova_poshta_id'], ['id'])
    op.create_foreign_key('posts_ukr_poshta_id_fkey', 'posts', 'ukr_poshta', ['ukr_poshta_id'], ['id'])
    op.drop_table('post_ukrposhta_association')
    op.drop_table('post_novaposhta_association')
    # ### end Alembic commands ###
