"""created tables and extra fields for anonym user

Revision ID: e717fe60e2a5
Revises: 485d11298cf8
Create Date: 2024-01-30 15:54:33.087058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e717fe60e2a5'
down_revision = '485d11298cf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_anon_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_anon_id')
    )
    op.create_table('basket_number_anon_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anonymous_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anonymous_user_id'], ['anonymous_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('basket_anon_users', sa.Column('basket_number_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'basket_anon_users', 'basket_number_anon_users', ['basket_number_id'], ['id'])
    op.add_column('orders', sa.Column('anonymous_user_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('basket_number_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'anonymous_users', ['anonymous_user_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'basket_number_anon_users', ['basket_number_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'basket_number_id')
    op.drop_column('orders', 'anonymous_user_id')
    op.drop_constraint(None, 'basket_anon_users', type_='foreignkey')
    op.drop_column('basket_anon_users', 'basket_number_id')
    op.drop_table('basket_number_anon_users')
    op.drop_table('anonymous_users')
    # ### end Alembic commands ###
