"""added review table

Revision ID: ec99fb476df2
Revises: 1a2a79cca82b
Create Date: 2023-11-05 23:18:50.064538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec99fb476df2'
down_revision = '1a2a79cca82b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('rating', sa.Enum('five_stars', 'four_stars', 'three_stars', 'two_stars', 'one_star', name='rating'), nullable=True),
                    sa.Column('description', sa.String(length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('is_checked', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('images', sa.Column('review_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'reviews', ['review_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'review_id')
    op.drop_table('reviews')
    # ### end Alembic commands ###
