"""add_main_image_for_images

Revision ID: ef6bb4b54a5d
Revises: ff4599998fbb
Create Date: 2023-10-27 15:23:42.035099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6bb4b54a5d'
down_revision = 'ff4599998fbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('main_image', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'main_image')
    # ### end Alembic commands ###
